### ISSUE TITLE
x-correlation issue

### ISSUE THREAD

**Issue by MisarahAbdelaziz** [jmbarrojr/SurfaceRoughnessStatistics#4]
Hi, I tried to use the code with simple 3D sinewave surface. However I have a bug when calculating x correlation
"
Error using matlab.internal.math.interp1
Sample points must be unique and sorted in ascending order.

Error in interp1 (line 154)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in ProcessSurfaceStatistics>CorrelationLenght (line 299)
Rlx = interp1(Zcorr(s:end),lags(s:end),1./exp(1),'linear');
".
I replaced this line with calculated value of Rlx and it works well and managed to create the folder, so I believe this is the only problem I have.

kindly find the surface.mat

Thanks in advance.

**Comment by MisarahAbdelaziz** [comment]
[S3D_16_08_08.zip](https://github.com/jmbarrojr/SurfaceRoughnessStatistics/files/6145564/S3D_16_08_08.zip)

**Comment by MisarahAbdelaziz** [comment]
Dear Dr Julio,

Thanks a lot for your help.

Best regards,
Misarah
________________________________

**Comment by jmbarrojr** [comment]
Dear Misarah,

I apologize for the error you were having. I knew the calculations for the correlation length were a little brittle. It worked for all limited cases I tested, but it did mean it would for for all. 
Thank you for have opened the issue and for using the code.
BTW, did you check if the updated code gives you the correlation length value that you expected?

Best,
Julio

**Comment by MisarahAbdelaziz** [comment]
Dear Dr Julio,

Thanks again for your help and the great effort you do to generalise the code. I believe it will be a huge step for researchers. According to my calculations all other parameters are the same. However I didn't use the correlation before in my post processing analysis. But it works well now after your modification.
Also, I suggest to make some examples for how should the user define his surface in 1d or 3d ones. It takes me some time to realise what is the best format of .mat file the code can read.

Finally, I would like to thank you again for this astonishing work.

Best regards,
Misarah

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
